version: '1.0.{build}'
branches:
  only:
    - master
image: Visual Studio 2017
before_build:
- cd src/Mvc
build_script:
- dotnet build DotNetDeployments.csproj
test_script:
  - cd ../../test
  - dotnet test DotNetDeployments.Tests.csproj
